<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BntBuscar</name>
   <tag></tag>
   <elementGuidId>56805f23-2563-421a-a944-7030027abab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[1]</value>
      <webElementGuid>69317270-93fb-4349-9c96-f4c7ad0182fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
