<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Busca</name>
   <tag></tag>
   <elementGuidId>33bbf99c-0ee1-4df9-9acf-97bf3ff6620d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[1][count(. | //*[@title = 'Pesquisar']) = count(//*[@title = 'Pesquisar'])]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pesquisar</value>
      <webElementGuid>5f0ece23-8141-4103-a83b-45517718253f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[1]</value>
      <webElementGuid>632d0eee-7d25-41c4-a2cb-97b8745020a0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
